### ISSUE TITLE
Google-RPC CDF

### ISSUE THREAD

**Issue by LessyLee** [serhatarslan-hub/bolt_cc_ns3#1]
Hello, your project does not show the NS3 large-scale simulation workload in your paper. Can you provide relevant documents? Especially Google READ RPCs.

Looking forward to your reply

**Comment by serhatarslan-hub** [comment]
Hi,

Thank you for showing interest in our work!

Unfortunately the Google workload has not been cleared for publishing in this work. However, there are other works from Google that are going to share more details about their workloads in the near future (in the process of publishing).

You can find the other public workloads we used on [this link](https://github.com/PlatformLab/HomaSimulation/tree/omnet_simulations/RpcTransportDesign/OMNeT%2B%2BSimulation/homatransport/sizeDistributions).

Sincerely,
